### ISSUE TITLE
No trace of a unix socket in /var/credentials-fetcher/socket upon compiling for ubuntu 18.04

### ISSUE THREAD

**Issue by nvp152** [aws/credentials-fetcher#12]
**Problem**
 I am compiling this code for ubuntu 18.04 in docker. The artifact compiles fine and i can run it but I am not seeing a socket being created under /var/credentials-fetcher/socket. I am probably missing something obvious. Clearly without a socket, any attempt at using grpc_cli or just using the daemon is impossible.

This is what I see when I run the compiled artifact. I should point, in passing, that i tried setting environment variables (e.g. CF_UNIX_DOMAIN_SOCKET_DIR) and that those don't are not getting applied.

```
# ./credentials-fetcherd
krb_files_dir = /var/credentials-fetcher/krbdir
logging_dir = /var/credentials-fetcher/logging
unix_socket_dir = /var/credentials-fetcher/socket
Thread 0: top of stack near 0x7f23cbdf4e60; argv_string=grpc_thread
Thread 0: top of stack near 0x7f23cb5f3e60; argv_string=krb_ticket_refresh_thread
```

**Replicating**
This is the dockerfile that compiles and builds the artifact for ubuntu 18.04

```
FROM ubuntu:18.04

RUN apt update \
    && apt full-upgrade -y \
    && apt install -y software-properties-common apt-transport-https dnsutils ldap-utils python3-pip wget git vim \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

# Mono
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    && echo "deb https://download.mono-project.com/repo/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/mono-official-stable.list
# CMake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/kitware.list

RUN apt update \
    && apt install -y libglib2.0-dev libboost-dev libkrb5-dev libsystemd-dev libboost-all-dev libssl-dev \
    && apt install -y cmake mono-complete

RUN cd /root && git clone https://github.com/aws/credentials-fetcher \
    && mkdir -p credentials-fetcher/build \
    && mkdir -p /usr/lib64/glib-2.0/ \
    && ln -s '/usr/lib/x86_64-linux-gnu/glib-2.0/include/' '/usr/lib64/glib-2.0/include' \
    && cd credentials-fetcher/build && cmake ../ && make -j && make install

WORKDIR /root/credentials-fetcher/build
    
CMD ["/bin/bash"]
```

**Comment by smhmhmd** [comment]
@nvp152 

Ubuntu support needs to be added here just like Fedora:
https://github.com/aws/credentials-fetcher/blob/mainline/CMakeLists.txt#L8

>This is the dockerfile that compiles and builds the artifact for ubuntu 18.04

This daemon runs as a process in the host, not in a container. It would be interesting if you have a new use-case.

**Comment by smhmhmd** [comment]
@nvp152 
I have a PR to remove Fedora checks so that errors are obvious during compilation
https://github.com/aws/credentials-fetcher/compare/mainline...smhmhmd:credentials-fetcher:mainline

**Comment by smhmhmd** [comment]
@nvp152 
pushed PR https://github.com/aws/credentials-fetcher/commit/b72d75a094a3ef8280687b3065a823757137f962, please try on ubuntu again

**Comment by nvp152** [comment]
I'd love to try it. However, i have 2 basic questions about getting this working end-to-end.

1. If I understood correctly the service supposed to run right in the kubernetes containers (aka as a non-domain-joined container host).
2. Assuming point  above is correct, one then has to create a credential spec - is anything special needed in the spec's "HostAccountConfig" value to get this to work?
3. Anything else?

**Comment by smhmhmd** [comment]
>If I understood correctly the service supposed to run right in the kubernetes containers (aka as a non-domain-joined container host).

I only tested on Fedora and AL2022 (beta), but any errors should be easily visible now.
If it still does not work on Ubuntu, we would really appreciate a PR from you.

If you like, we can also have a  hands-on session, we can show you how we are testing.

As of now, the daemon can be installed in a domain-joined host ( I have a PR out for domainless/non-domainjoined host as well). 
To do a quick test:
*  create gMSA accounts with names WebApp01 and WebApp03
* start the daemon (make sure socket exists in /var/credentials-fetcher/socket/, also use journalctl to check logs)
*  Run client as `    ./api/tests/gmsa_test_client
`

**Comment by fordth** [comment]
Hi we are very interested in using this on a host machine running Ubuntu 20.04.5 but seem to be failing to compile when it comes to grpc. Any information to help us compile on Ubuntu would be greatly appreciated, thank you.

**Comment by smhmhmd** [comment]
@fordth 

> failing to compile when it comes to grpc.

Thanks to @sega19 for steps to build gRPC, these steps build on ubuntu-20.04.
cmake and make should work for credentials-fetcher after this.

> git clone --recurse-submodules -b v1.56.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc
> cd grpc/
> mkdir cmake/build
> cd cmake/build
> cmake -DgRPC_INSTALL=ON       -DgRPC_BUILD_TESTS=OFF    ../..
> make -j 4
> make install

**Comment by fordth** [comment]
> @fordth
> 
> > failing to compile when it comes to grpc.
> 
> Thanks to @sega19 for steps to build gRPC, these steps build on ubuntu-20.04. cmake and make should work for credentials-fetcher after this.
> 
> > git clone --recurse-submodules -b v1.56.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc
> > cd grpc/
> > mkdir cmake/build
> > cd cmake/build
> > cmake -DgRPC_INSTALL=ON       -DgRPC_BUILD_TESTS=OFF    ../..
> > make -j 4
> > make install

This is great! Thank you for the response, I will give this a try!

**Comment by fordth** [comment]
I was able to successfully build grpc with the steps outlined above.
However when compiling credential-fetcher, I get the following:

cmake ../ && make -j

CMake Warning at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version 23.1 doesn't match library version 4.23.1

**Comment by smhmhmd** [comment]
@fordth 

I got past the above cmake warning.

* Make sure you have a new instance/install of ubuntu-20.04.
* Update cmake to cmake-3.27 using `sudo snap install cmake --classic`
* Install bazel as per https://bazel.build/install/ubuntu
* Clone protobuf using `git clone https://github.com/protocolbuffers/protobuf.git`
* Use bazel to build and install protobuf
* Clone grpc as in `git clone --recurse-submodules -b v1.56.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc`

I have some more remaining steps to build credentials-fetcher like dotnet etc.

**Comment by fordth** [comment]
@smhmhmd Thank you for the feed back. I was able to get much further now, but I end up getting the following error:

/usr/bin/ld: ../CMakeFiles/cf_gmsa_service_private.dir/__/auth/kinit_client/kinit.c.o: in function `k5_kinit':
kinit.c:(.text+0x18de): undefined reference to `k5_cc_store_primary_cred'
collect2: error: ld returned 1 exit status

**Comment by fordth** [comment]
@smhmhmd Im having a real hard time getting credential fetcher to compile on Ubuntu 20.04.5 (Or what specific version of Ubuntu should be used).  I think what might help, is what specific versions of CMake, g++, protobuc, gRPC, .Net SDK should be used for compiling? Even abseil seems to need to be a specific version. Any help would be greatly appreciated, thank you

**Comment by smhmhmd** [comment]
@fordth 

Found the issue, I was able to build on ubuntu-22.04, should work for ubuntu-20.04 as well.
I can give you the changes, you can make a PR, after some cleanup.
It does not need as many changes as discussed before.

We can discuss the changes, please send me an email at samiull at amazon dot com.

```
ubuntu@ip-10-0-0-126:~/credentials-fetcher/build$ ls
CMakeCache.txt       config                                                metadata
CMakeFiles           config.h                                              metadata_invalid_sample.json
CTestTestfile.cmake  credentials-fetcherd                                  metadata_sample.json
Makefile             credentials_fetcher_utf16_private.exe                 renewal
api                  credentials_fetcher_utf16_private.runtimeconfig.json
cmake_install.cmake  daemon
ubuntu@ip-10-0-0-126:~/credentials-fetcher/build$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

`

**Comment by fordth** [comment]
@smhmhmd Great, thank you, I sent you an email

**Comment by smhmhmd** [comment]
@fordth 
I created a PR off your branch -  https://github.com/fordth/credentials-fetcher/pull/1 
Could you please accept the PR into your branch.

I added conditional compilation for builds on both Amazon Linux 2023 and Ubuntu.

**Comment by smhmhmd** [comment]
Please check https://github.com/aws/credentials-fetcher/tree/mainline/docker
